config/routes.rb
Rails.application.routes.draw do
  root 'home#show'
  get "/auth/oauth2/callback" => "auth0#callback"
  get "/auth/failure" => "auth0#failure"
  get "/profile" => "home#profile"
  get "/auth/logout" => "auth0#logout"
  resources :books
  resources :shelves
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :shelves, dependent: :destroy
  has_many :users, through: :shelves
  scope :within_shelf, ->(place,user) {
    joins(:shelves,:users)
    .where(shelves: {place: place, users: {id: user.id}})
  }
end

app/models/shelf.rb
class Shelf < ApplicationRecord
  enum place: [:wishlist, :bought, :reading, :done]
  belongs_to :user
  belongs_to :book
  validates :user_id, uniqueness: {scope: :book_id}
  scope :by_user, ->(user) { where(user_id: user)} 
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :name
    attr_accessor :image
    has_many :shelves, dependent: :destroy
    has_many :books, through: :shelves
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Auth0Helper
end

app/controllers/auth0_controller.rb
class Auth0Controller < ApplicationController
  include LogoutHelper
  def logout
      reset_session
      redirect_to logout_url.to_s
  end

  def callback
    session[:userinfo] = request.env['omniauth.auth']
    find_or_create_user!
    redirect_to '/books'
  end

  def failure
    @error_msg = request.params['message']
  end

  private

    def find_or_create_user!
        email_id=session[:userinfo]["info"]["email"]
        User.find_or_create_by!(email: email_id)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  def index
    if(params[:place].nil?)
      @books=Book.all
    else
      @books=Book.within_shelf(
        params[:place],
        current_user)
    end
  end

  def show
    current_shelf=@book.shelves.by_user(current_user).first
    if current_shelf.blank?
      @shelf=Shelf.new
    else
      @shelf=current_shelf
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  private
    def set_book
      @book = Book.find(params[:id])
    end

    def book_params
      params.require(:book).permit(:title, :author)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :authenticate_user!, only: [:profile]

  def show
  end

  def profile
  end
end

app/controllers/newone_controller.rb
class NewoneController < ApplicationController

  before_action :authenticate_user!, only: [:profile]

  def show
  end

  def profile
  end
end

app/controllers/shelves_controller.rb
class ShelvesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_shelf, only: [:update]

  def create
    @shelf=Shelf.find_or_create_by(
      user_id: current_user.id,
      book_id: shelf_params[:book_id],
      place: shelf_params[:place]
    )
    redirect_to @shelf.book
  end

  def update
      @shelf.update(shelf_params)
      redirect_to @shelf.book
  end

  private

    def set_shelf
      @shelf = Shelf.find(params[:id])
    end
    def shelf_params
      params.require(:shelf).permit(:place, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth0_helper.rb
module Auth0Helper
  private
    def user_signed_in?
        session[:userinfo].present?
    end

    def authenticate_user!
        if user_signed_in?
            @current_user=build_user
        else
            redirect_to root_path
        end
    end

    def current_user
        @current_user
    end

    def build_user
        user_info=session[:userinfo]["info"]
        email_id=user_info["email"]
        user=User.find_by(email: email_id)
        user.name=user_info["name"]
        user.image=user_info["image"]
        user
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/logout_helper.rb
module LogoutHelper
  def logout_url
    domain = 'thielsen.eu.auth0.com'
    request_params = {
        returnTo: root_url,
        client_id: Rails.application.credentials.auth0[:client_id]
    }

    URI::HTTPS.build(
      host: domain,
      path: '/v2/logout',
      query: to_query(request_params))
  end

  private

  def to_query(hash)
    hash.map { |k, v| "#{k}=#{URI.escape(v)}" unless v.nil? }.reject(&:nil?).join('&')
  end
end

app/helpers/session_helper.rb
module SessionHelper
  def get_state
    state = SecureRandom.hex(24)
    session['omniauth.state'] = state
    state
  end
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="actions">
    <p></p><%= form.submit %>
  </div>
<% end %>

app/views/books/_shelf_form.html.erb
<%= form_with(model: shelf, local: true) do |form| %>
  <div class="field">
    <%= form.label :place,"Shelf"%>
    <%= form.select(:place,
        options_for_select(Shelf.places.keys,shelf.place),
        :include_blank=>true,
        id: :shelf_place)
    %>
  </div>
  <%= form.hidden_field :book_id, :value=>params[:id] %>
  <div class="actions">
    <p></p><%= form.submit "Move to shelf" %>
  </div>
<% end %>

app/views/books/_shelf_list.html.erb
<section class="shelves">
    <%= link_to "All",books_path %>
    <% Shelf.places.keys.each do |shelf| %>
        <%= link_to shelf.capitalize,books_path(place: shelf) %>
    <% end %>
</section>

app/views/books/index.html.erb
<div class="books">
  <%= render 'shelf_list' %>
  <%= link_to "Add New Book", new_book_path , class: 'new_book' %>
  <section class="book_list">
      <% @books.each do |book| %>
        <article class="book_entry">
          <h2><%= link_to book.title.capitalize, book %></h2>
          <h3><%= book.author %></h3 >
        </article>
      <% end %>
  </section>
</div>

app/views/books/new.html.erb
<div class="card">
  <h1>New Book</h1>
  <%= render 'form', book: @book %>
  <%= link_to 'Back', books_path %>
</div>

app/views/books/show.html.erb
<article class="book card">
  <h1><%= @book.title %></h1>
  <p>
    <strong>Author:</strong>
    <%= @book.author %>
  </p>
  <%= render 'shelf_form', shelf: @shelf %>
</article>

app/views/home/profile.html.erb
<section class="profile card">
  <h2><img src='<%= current_user.image %>' /></h2>
  <h1><%= current_user.name %></h1>
  <%= link_to "Logout",auth_logout_path, class: "btn red" %>
</section>

app/views/home/show.html.erb
<section class="welcome card">
  <h1>Bookshelf</h1>
  <h2>Built on Ruby on Rails secured with Auth0</h2>
  <a class="btn green" href="/auth/auth0">Login</a>
</section>
<%= debug session[:userinfo] %>

app/views/layouts/_navbar.html.erb
<nav>
    <div>
        <%= image_tag "book.svg",class: "logo" %>
        <h1>
        <%= link_to "BookShelf", books_path%>
        </h1>
    </div>
    <ul>
        <% if user_signed_in? %>
            <li><%= link_to "Profile",profile_path %></li>
            <li><%= link_to "Logout",auth_logout_path %></li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header><%= render 'layouts/navbar' %></header>
    <%= yield %>
  </body>
</html>

app/views/newone/test.html.erb
<html>
  <head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
  </head>
  <body>
  <div class="header"
  <h3>Chitter: Latest peeps</h3>
  </div>
  <div class="sidebar">
    <a href="/login"><i class="fa fa-sign-in"></i> Login</a>
    <a href="/signup"><i class="fa fa-user-plus"></i> Signup</a>
  </div>
  <div class="peeps">
    <li class="peep" id="peep-1">
      <p>My first peep!<br><br></p>
      <small>
        <span class="name">User Person</span>
        @user1
        <span class="time">2019-02-02 19:08:38 UTC</span>
      </small>
      </li>
    <li class="peep" id="peep-1">
      <p>Another test peep<br><br></p>
      <small>
        <span class="name">User Person</span>
        @user1
        <span class="time">2019-02-02 19:08:38 UTC</span>
      </small>
      </li>
    <li class="peep" id="peep-1">
      <p>A new user testing a peep here<br><br></p>
      <small>
        <span class="name">User Person</span>
        @user1
        <span class="time">2019-02-02 19:08:38 UTC</span>
      </small>
      </li>
    <li class="peep" id="peep-3">
      <p>Testing with user2<br><br></p>
      <small>
        <span class="name">USer 2</span>
        @user2
        <span class="time">2019-02-02 22:22:46 UTC</span>
      </small>
      </li>
  <br>
  </div>
  </body>
</html>